export const PRE_DIAGNOSTIC_FEATURES = [
  "Age",
  "Gender",
  "Smoking_History",
  "Alcohol_Consumption",
  "Obesity_BMI",
  "Diabetes",
  "Inflammatory_Bowel_Disease",
  "Family_History",
  "Diet_Risk",
  "Physical_Activity",
  "Abdominal Pain",
  "Bleeding PR",
  "Weight Loss",
  "Bowel Change",
  "Tenesmus",
  "Anemia related symptoms",
  "Abdominal Mass Palpable",
  "PR Exam Suspicious",
  "ECOG status",
  "Pallor",
  "Hemoglobin",
  "FIT/FOBT",
  "CEA_Level",
  "Liver function Test",
  "serum Albumin",
] as const;

export type PatientData = Record<
  (typeof PRE_DIAGNOSTIC_FEATURES)[number],
  unknown
>;

export const defaultPatientData: PatientData = {
  Age: 0,
  Gender: "Male",
  Smoking_History: "No",
  Alcohol_Consumption: "No",
  Obesity_BMI: 0,
  Diabetes: "No",
  Inflammatory_Bowel_Disease: "No",
  Family_History: "No",
  Diet_Risk: "Low",
  Physical_Activity: "Moderate",
  "Abdominal Pain": "No",
  "Bleeding PR": "No",
  "Weight Loss": "No",
  "Bowel Change": "No",
  Tenesmus: "No",
  "Anemia related symptoms": "No",
  "Abdominal Mass Palpable": "No",
  "PR Exam Suspicious": "No",
  "ECOG status": 0,
  Pallor: "No",
  Hemoglobin: 0,
  "FIT/FOBT": "Negative",
  CEA_Level: 0,
  "Liver function Test": "Normal",
  "serum Albumin": 0,
};